# .rubocop.yml

AllCops:
  NewCops: enable # Good practice to include this

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: true
  Max: 120

Style/NegatedIfElseCondition:
  Enabled: False

Style/MethodCallWithoutArgsParentheses:
  Enabled: False

Layout/ExtraSpacing:
  Enabled: False

Style/SymbolArray:
  Enabled: False

Metrics/MethodLength:
  Enabled: False

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: False

Layout/EmptyLines:
  Enabled: False

Naming/VariableName:
  Enabled: true
  AllowedIdentifiers:
    - W_o
    - expected_W_o
    - actual_W_o
    - grad_W_o
    - initial_W_o
    - W_h
    - expected_W_h
    - actual_W_h
    - grad_W_h
    - initial_W_h

Metrics/ClassLength:
  Enabled: False

Style/MultipleComparison:
  Enabled: False

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallBraceLayout:
  Enabled: False

Metrics/AbcSize:
  Enabled: False
